WEBSITESLK/WEBSITESLK/Controllers/CarInfo1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WEBSITESLK.Models;

namespace WEBSITESLK.Controllers
{ [Authorize]
    public class CarInfo1Controller : Controller
    {
        private Car db = new Car();
        // GET: CarInfo1
        public ActionResult Index()
        {

            return View(db.CarInfo1.ToList());
        }
        // GET: CarInfo1/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarInfo1 carInfo1 = db.CarInfo1.Find(id);
            if (carInfo1 == null)
            {
               
                return HttpNotFound();
            }
            return View(carInfo1);
        }

        // GET: CarInfo1/Create
        public ActionResult Create()
        {
            
            return View();
        }

        // POST: CarInfo1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VIN,Brand,Model,Price,StoreLoc,Owner,isimgup")] CarInfo1 carInfo1)
        {
            if (ModelState.IsValid)
            {
                db.CarInfo1.Add(carInfo1);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(carInfo1);
        }

        // GET: CarInfo1/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarInfo1 carInfo1 = db.CarInfo1.Find(id);
            if (carInfo1 == null)
            {
                return HttpNotFound();
            }
            return View(carInfo1);
        }
        // POST: CarInfo1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VIN,Brand,Model,Price,StoreLoc,Owner")] CarInfo1 carInfo1)
        {
            if (ModelState.IsValid)
            {
                db.Entry(carInfo1).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(carInfo1);
        }

        // GET: CarInfo1/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            CarInfo1 carInfo1 = db.CarInfo1.Find(id);
         
            if (carInfo1 == null)
            {
                return HttpNotFound();
            }
            return View(carInfo1);
        }

        // POST: CarInfo1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            CarInfo1 carInfo1 = db.CarInfo1.Find(id);
            db.CarInfo1.Remove(carInfo1);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WEBSITESLK/WEBSITESLK/Controllers/ImagesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.WebPages;
using WEBSITESLK.Models;

namespace WEBSITESLK.Controllers
{
    public class ImagesController : Controller
    {
        private Car db = new Car();
      
           [Authorize]
        // GET: Images
        [HttpGet]
        public ActionResult AddVehicleImage(string id)
        {
            CarInfo1 imgstatus = db.CarInfo1.Find(id);
         
            return View(imgstatus);
        }
        [HttpPost]
        public ActionResult AddVehicleImage(string id,image ige, HttpPostedFileBase imgf)
        {
            if (imgf != null)
            {

                using (Car img = new Car())
                {
                    CarInfo1 cimg = new CarInfo1();
                    var v = img.CarInfo1.Find(id);
                    if (v != null)
                    {
                        v.isimgup = true;
                        img.SaveChanges();
                    }
                }

                string filename = id+Path.GetExtension(imgf.FileName) ;
                string path = Path.Combine(Server.MapPath("~/Images/"), filename.ToString());
                imgf.SaveAs(path.ToString());
                Pics newimageupload = new Pics();
                ModelState.Clear();
                newimageupload.ImagesBlobFileInput(filename, path);

            }
            return RedirectToAction("success");
        }
        public ActionResult success()
        {
            return View();
        }
    }
}

WEBSITESLK/WEBSITESLK/Views/Images/AddVehicleImage.cshtml
    @model WEBSITESLK.Models.CarInfo1

@{
    ViewBag.Title = "AddVehicleImage";
}

<h2>AddVehicleImage</h2>


@using (Html.BeginForm("AddVehicleImage","Images",FormMethod.Post,new { enctype="multipart/form-data"}))
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>image</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
           @* @Html.LabelFor(model => model.image1, htmlAttributes: new { @class = "control-label col-md-2" })*@
            <div class="col-md-10">
               @* @Html.EditorFor(model => model.image1, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.image1, "", new { @class = "text-danger" })*@
                <input type="file" name="imgf" required />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Submit" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to vehicle details", "Index","CarInfo1")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

WEBSITESLK/WEBSITESLK/Views/Images/show.cshtml
@{
    ViewBag.Title = "show";
}

<h2>show</h2>
<dl class="dl-horizontal">
    <dt>
    </dt>
    <dd>
        <img src="..\..\Images\Lion.jpeg" width="250" height="300"/>
    </dd>
</dl>

WEBSITESLK/WEBSITESLK/Views/Images/success.cshtml
@model IEnumerable<WEBSITESLK.Models.CarInfo1>
@{
    ViewBag.Title = "success";
}
<h2>success</h2>
<p>
    Your Image has been uploaded!!!!!
</p>
@Html.ActionLink("Home", "Index", "Home")

@*@foreach (var item in Model)
{
    <img src="..\..\Images\+@item.VIN+.jpeg" alt="problem!!!" width="50" height="50" />
}*@